services:

  sarch-models-ms:
    image: javergarav/sarch-models-ms:latest
    container_name: sarch-models-ms
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
    ports:
      - "4000:4000"
    networks:
      - sarch-network

  sarch-checks-ms:
    image: javergarav/sarch-checks-ms:latest
    container_name: sarch-checks-ms
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
    ports:
      - "4100:4100"
    networks:
      - sarch-network

  sarch-redesigns-ms:
    image: javergarav/sarch-redesigns-ms:latest
    container_name: sarch-redesigns-ms
    ports:
      - "4200:4200"
    networks:
      - sarch-network

  sarch-ag:
    image: javergarav/sarch-ag:latest
    container_name: sarch-ag
    environment:
      - SARCH_MODELS_MS_URI=http://sarch-models-ms:4000
      - SARCH_CHECKS_MS_URI=http://sarch-checks-ms:4100
      - SARCH_REDESIGNS_MS_URI=http://sarch-redesigns-ms:4200
    depends_on:
      - sarch-models-ms
      - sarch-checks-ms
      - sarch-redesigns-ms
    ports:
      - "6500:6500"
    networks:
      - sarch-network

  sarch-fe:
    image: javergarav/sarch-fe:latest
    container_name: sarch-fe
    environment:
      - SARCH_AG_URI=http://sarch-ag:6500
    depends_on:
      - sarch-ag
    ports:
      - "8080:8080"
    networks:
      - sarch-network

networks:
  sarch-network:
